version: "3.8"

services:
  mongo:
    container_name: mongodb
    image: mongo:4
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: senha
      MONGO_INITDB_DATABASE: qrcodedb
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
